PRAGMA foreign_keys=ON;
BEGIN TRANSACTION;
CREATE TABLE account_type(id integer primary key autoincrement, name text);
INSERT INTO "account_type" VALUES(1,'Наличные');
INSERT INTO "account_type" VALUES(2,'Актив');
INSERT INTO "account_type" VALUES(3,'Дебетовая карта');
INSERT INTO "account_type" VALUES(4,'Кредитная карта');
INSERT INTO "account_type" VALUES(5,'Долги');
CREATE TABLE account(id integer primary key autoincrement, name text, type integer, balance real, descr text, ccod int default 1, hidden int default 0, parent int default 0, top int, system int default 0);
INSERT INTO "account" VALUES(1,'Актив',0,0,'',1,0,0,1,1);
INSERT INTO "account" VALUES(2,'Пассив',0,0,'',1,0,0,2,1);
INSERT INTO "account" VALUES(3,'Доход',0,0,'',1,0,0,3,1);
INSERT INTO "account" VALUES(4,'Расход',0,0,'',1,0,0,4,1);
INSERT INTO "account" VALUES(5,'Корректировка',4,0,'',1,0,4,4,1);
INSERT INTO "account" VALUES(6,'Собственные средства',4,0,'',1,0,0,6,1);
INSERT INTO "account" VALUES(7,'Начальное сальдо',5,0.0,'',1,0,6,6,1);
CREATE TABLE operation(id integer primary key autoincrement, dt date, acc_from integer, acc_to integer, summ real, descr text, agent int default 0, plan_id int default 0);
CREATE TABLE agent(id integer primary key autoincrement, name text, city text, address text, phone text, contact text);
CREATE TABLE currency(id integer primary key autoincrement, name text, icod int, scod text, kurs real);
INSERT INTO "currency" VALUES(1,'Российский рубль',NULL,'RUB',1.0);
INSERT INTO "currency" VALUES(2,'Доллар США',NULL,'USD',32.2676);
INSERT INTO "currency" VALUES(3,'Евро',NULL,'EUR',43.7645);
CREATE TABLE account_oper(id integer primary key autoincrement, a_id int, o_id int, summ real, direction int default 0);
CREATE TABLE plan_oper(id integer primary key autoincrement, day int, month int, year int, descr text);
CREATE TABLE plan_account_oper(id integer primary key autoincrement, a_id int, o_id int, summ real, direction int default 0);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('account_type',5);
INSERT INTO "sqlite_sequence" VALUES('account',7);
INSERT INTO "sqlite_sequence" VALUES('currency',3);
COMMIT;
